name: Testing
on:
  push:
  pull_request:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Test application
        run: go test ./...
      - name: Compile application
        run: go build -o tabloid-tmp && rm -rf tabloid-tmp
