name: Testing
on:
  push:
  pull_request:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.0.0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test application
        run: go test ./...
      - name: Compile application
        run: go build -o tabloid-tmp && rm -rf tabloid-tmp
